# Generated by Django 4.2.7 on 2023-11-20 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fulfillmentapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Goods',
            new_name='Product',
        ),
        migrations.RenameModel(
            old_name='Sellers',
            new_name='Seller',
        ),
    ]
