# Generated by Django 4.2.7 on 2023-12-09 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fulfillmentapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='seller',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='fulfillmentapp.seller', verbose_name='Продавец'),
        ),
        migrations.AddField(
            model_name='product',
            name='seller',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='fulfillmentapp.seller', verbose_name='Продавец'),
        ),
        migrations.AlterField(
            model_name='producttype',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_types', to='fulfillmentapp.seller', verbose_name='Продавец'),
        ),
    ]
