# Generated by Django 4.2.7 on 2023-11-23 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fulfillmentapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='telegram_chat_id',
            field=models.CharField(blank=True, default=''),
        ),
    ]
