# Generated by Django 4.2.7 on 2023-11-20 19:15

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fulfillmentapp', '0002_rename_goods_product_rename_sellers_seller'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='fulfillmentapp.product')),
                ('address', models.TextField()),
                ('driver_fio', models.CharField(max_length=50)),
                ('car_number', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('qr', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('login', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.RenameField(
            model_name='product',
            old_name='owner',
            new_name='seller',
        ),
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='id',
        ),
        migrations.RemoveField(
            model_name='product',
            name='time_create',
        ),
        migrations.AddField(
            model_name='product',
            name='article',
            field=models.IntegerField(default=10001, primary_key=True, serialize=False, unique=True, validators=[django.core.validators.MinValueValidator(10000)]),
        ),
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AddField(
            model_name='product',
            name='numbers',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(blank=True, default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(default=None, max_length=30),
        ),
    ]
