# Generated by Django 4.2.7 on 2023-12-10 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fulfillmentapp', '0002_delivery_seller_product_seller_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producttype',
            name='article',
            field=models.CharField(default=None, max_length=30, verbose_name='Артикул маркетплейса'),
        ),
        migrations.AlterField(
            model_name='producttype',
            name='price',
            field=models.IntegerField(default=0, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='producttype',
            name='weight',
            field=models.IntegerField(default=1, verbose_name='Вес (кг)'),
        ),
    ]
