# Generated by Django 4.2.7 on 2023-11-23 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fulfillmentapp', '0003_alter_seller_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='email',
            field=models.EmailField(blank=True, default=None, max_length=254, verbose_name='Почта'),
        ),
    ]
