# Generated by Django 4.2.7 on 2023-12-10 02:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fulfillmentapp', '0003_alter_producttype_article_alter_producttype_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='delivery',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='fulfillmentapp.delivery', verbose_name='Отгрузка'),
        ),
    ]
