# Generated by Django 4.2.7 on 2023-12-10 03:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fulfillmentapp', '0004_alter_product_delivery'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producttype',
            options={'verbose_name': 'Тип товара', 'verbose_name_plural': 'Типы товаров'},
        ),
        migrations.AddField(
            model_name='delivery',
            name='product_type',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='fulfillmentapp.producttype', verbose_name='Тип товара'),
            preserve_default=False,
        ),
    ]
