# Generated by Django 4.2.7 on 2023-11-23 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fulfillmentapp', '0004_alter_seller_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallAssistant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram', models.CharField(blank=True, default=None, max_length=30, verbose_name='Телеграм')),
                ('telegram_chat_id', models.CharField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'Ассистент',
                'verbose_name_plural': 'Ассистенты',
            },
        ),
    ]
