# Generated by Django 4.2.7 on 2023-11-25 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fulfillmentapp', '0007_remove_delivery_qr_delivery_barcode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='seller',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='fulfillmentapp.seller', verbose_name='Продавец'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='fulfillmentapp.seller', verbose_name='Продавец'),
        ),
    ]
