# Generated by Django 4.2.7 on 2023-11-25 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fulfillmentapp', '0008_delivery_seller_alter_product_seller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(blank=True, default='В пути до вас', max_length=20, verbose_name='Статус'),
        ),
    ]
