# Generated by Django 4.2.7 on 2023-11-26 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fulfillmentapp', '0009_alter_product_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(blank=True, default='В пути до вас', max_length=40, verbose_name='Статус'),
        ),
    ]
