# Generated by Django 4.2.7 on 2023-11-27 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fulfillmentapp', '0013_alter_product_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='callassistant',
            options={'verbose_name': 'Ассистент', 'verbose_name_plural': 'Ассистенты (колл-центр)'},
        ),
        migrations.AlterModelOptions(
            name='operator',
            options={'verbose_name': 'Оператор', 'verbose_name_plural': 'Операторы склада'},
        ),
        migrations.AlterField(
            model_name='delivery',
            name='bill',
            field=models.BinaryField(blank=True, default=None, null=True, verbose_name='Счет'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='label',
            field=models.BinaryField(blank=True, default=None, null=True, verbose_name='Этикетка'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='marketplace_barcode',
            field=models.BinaryField(null=True, verbose_name='Штрих-код для маркетплейса'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='wrapper_barcode',
            field=models.BinaryField(blank=True, default=None, null=True, verbose_name='Штрих-код для тары'),
        ),
    ]
