# Generated by Django 4.2.7 on 2023-11-27 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fulfillmentapp', '0014_alter_callassistant_options_alter_operator_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='bill',
            field=models.BinaryField(blank=True, default=None, editable=True, null=True, verbose_name='Счет'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='car_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Номер авто'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='driver_fio',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ФИО водителя'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='label',
            field=models.BinaryField(blank=True, default=None, editable=True, null=True, verbose_name='Этикетка'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='marketplace_barcode',
            field=models.BinaryField(editable=True, null=True, verbose_name='Штрих-код для маркетплейса'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='delivery', serialize=False, to='fulfillmentapp.product', verbose_name='Товар'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='wrapper_barcode',
            field=models.BinaryField(blank=True, default=None, editable=True, null=True, verbose_name='Штрих-код для тары'),
        ),
    ]
